"use client";

import { useState } from "react";
import Link from "next/link";
import { BeforeAfterToggle } from "./BeforeAfterToggle";
import { Button } from "@/components/ui/Button";

interface CaseStudy {
  id: string;
  category: "jawline" | "eyes" | "skin" | "all";
  name: string;
  age: string;
  focusArea: string;
  beforeSrc: string;
  afterSrc: string;
  metrics: { label: string; value: string }[];
  clinicalFinding: string;
}

const CASES: CaseStudy[] = [
  {
    id: "case-1",
    category: "eyes",
    name: "Elena R.",
    age: "32",
    focusArea: "Tear Trough & Midface Harmony",
    beforeSrc: "/images/transformations/female_studio_before.webp",
    afterSrc: "/images/transformations/female_studio_after.webp",
    metrics: [
      { label: "Periorbital Volume", value: "+35% Lift" },
      { label: "Tear Trough Shadow", value: "Restored" },
      { label: "Facial Symmetry", value: "96% Index" },
    ],
    clinicalFinding:
      "Tear trough hollowing diminished with subtle anterior cheek volume restoration, establishing natural youthful light reflection.",
  },
  {
    id: "case-2",
    category: "jawline",
    name: "Aakash M.",
    age: "28",
    focusArea: "Mandibular Angle & Jawline Sharpness",
    beforeSrc: "/images/transformations/male_jawline_before.webp",
    afterSrc: "/images/transformations/male_jawline_after.webp",
    metrics: [
      { label: "Jaw-to-Neck Separation", value: "+28% Definition" },
      { label: "Eye Openness", value: "Refreshed" },
      { label: "Submental Fullness", value: "Streamlined" },
    ],
    clinicalFinding:
      "Sharp lower mandibular definition and refined cervical angle, eliminating fatigue signals while preserving authentic facial character.",
  },
  {
    id: "case-3",
    category: "skin",
    name: "Claire D.",
    age: "35",
    focusArea: "Radiance & Harmonized Soft Tissue",
    beforeSrc: "/images/transformations/female_glow_before.webp",
    afterSrc: "/images/transformations/female_glow_after.webp",
    metrics: [
      { label: "Complexion Luminosity", value: "Hydrated Glow" },
      { label: "Cheek Volume Vector", value: "Elevated" },
      { label: "Smile Symmetry", value: "Balanced" },
    ],
    clinicalFinding:
      "Luminous complexion enhancement paired with midface lift and structured lateral support, elevating everyday charisma.",
  },
  {
    id: "case-4",
    category: "jawline",
    name: "Mateo S.",
    age: "31",
    focusArea: "Charisma & Structural Jawline Architecture",
    beforeSrc: "/images/transformations/male_lifestyle_before.webp",
    afterSrc: "/images/transformations/male_lifestyle_after.webp",
    metrics: [
      { label: "Facial Proportion", value: "Golden Ratio" },
      { label: "Grooming Harmony", value: "Optimized" },
      { label: "Profile Confidence", value: "Elevated" },
    ],
    clinicalFinding:
      "Integrated jawline sharpening and perioral harmonization, translating tired indoor baseline into magnetic real-world presence.",
  },
];

export function TransformationShowcase() {
  const [activeCategory, setActiveCategory] = useState<string>("all");

  const filteredCases =
    activeCategory === "all"
      ? CASES
      : CASES.filter((c) => c.category === activeCategory);

  return (
    <section id="transformations" className="scroll-mt-20 border-t border-border bg-surface-warm py-24 sm:py-32">
      <div className="mx-auto max-w-6xl px-6">
        {/* Section Header */}
        <div className="max-w-2xl">
          <p className="eyebrow text-[11px]">Clinical Visualizations</p>
          <h2 className="mt-4 font-serif text-4xl leading-[1.05] tracking-tight text-balance sm:text-5xl lg:text-6xl">
            See the targeted changes
            <span className="mt-1 block font-light italic text-accent">across real facial structures.</span>
          </h2>
          <div aria-hidden className="mt-6 h-px w-16 bg-accent" />
          <p className="mt-6 text-base leading-7 text-body-text">
            Every simulation is generated by our aesthetic intelligence algorithm — respecting natural anatomy,
            individual bone structure, and biological Golden Ratio balance.
          </p>
        </div>

        {/* Category Filters */}
        <div className="mt-10 flex flex-wrap gap-2">
          {[
            { id: "all", label: "All Transformations" },
            { id: "jawline", label: "Jawline & Mandibular Contour" },
            { id: "eyes", label: "Under-Eye & Tear Trough" },
            { id: "skin", label: "Skin Radiance & Midface Lift" },
          ].map((cat) => (
            <button
              key={cat.id}
              onClick={() => setActiveCategory(cat.id)}
              className={`rounded-full px-5 py-2 text-xs font-semibold tracking-wide transition-all ${
                activeCategory === cat.id
                  ? "bg-dark-surface text-white shadow-sm"
                  : "bg-surface text-muted hover:text-foreground border border-border"
              }`}
            >
              {cat.label}
            </button>
          ))}
        </div>

        {/* Grid of Interactive Comparisons */}
        <div className="mt-12 grid gap-10 md:grid-cols-2">
          {filteredCases.map((c) => (
            <div
              key={c.id}
              className="flex flex-col rounded-3xl border border-border bg-background p-6 shadow-medium transition-all hover:shadow-elevated"
            >
              {/* Interactive Comparison Component */}
              <BeforeAfterToggle
                beforeSrc={c.beforeSrc}
                afterSrc={c.afterSrc}
                beforeLabel="Current Baseline"
                afterLabel="Targeted Simulation"
                aspectRatio="aspect-[4/5]"
                className="w-full"
              />

              {/* Patient & Vector Details */}
              <div className="mt-6 flex items-start justify-between border-b border-border/80 pb-4">
                <div>
                  <h3 className="font-heading text-lg font-bold text-foreground">
                    {c.name}, <span className="text-sm font-normal text-muted">{c.age}</span>
                  </h3>
                  <p className="text-xs font-semibold tracking-wide text-accent">{c.focusArea}</p>
                </div>
                <span className="rounded-full bg-accent/10 px-3 py-1 text-[11px] font-bold text-accent">
                  AI Simulated
                </span>
              </div>

              {/* Metrics Row */}
              <div className="mt-4 grid grid-cols-3 gap-2 rounded-2xl bg-surface-warm p-3 text-center">
                {c.metrics.map((m) => (
                  <div key={m.label}>
                    <p className="text-[10px] uppercase tracking-wider text-muted">{m.label}</p>
                    <p className="font-heading text-xs font-bold text-foreground">{m.value}</p>
                  </div>
                ))}
              </div>

              {/* Clinical Finding Note */}
              <p className="mt-4 text-xs leading-relaxed text-secondary-text">
                <strong className="text-foreground">Clinical Observation:</strong> {c.clinicalFinding}
              </p>
            </div>
          ))}
        </div>

        {/* Bottom CTA block within showcase */}
        <div className="mt-16 rounded-3xl border border-accent/20 bg-dark-surface p-8 sm:p-12 text-center text-dark-foreground shadow-heavy">
          <p className="eyebrow text-gold text-[11px]">Instant Pre-Consultation Insight</p>
          <h3 className="mt-3 font-serif text-3xl sm:text-4xl text-balance">
            Discover what your own facial simulation reveals.
          </h3>
          <p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-dark-body">
            Upload your front photo today. In 60 seconds, receive your bespoke before &amp; after simulation
            and comprehensive 2-page Clinical Dossier directly to your inbox.
          </p>
          <div className="mt-8 flex justify-center">
            <Link href="/assessment">
              <Button size="lg" className="shadow-elevated">
                Start Your Facial Assessment
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}
