/**
 * The browser's side of illustration generation. It runs ONLY when the person
 * clicks "Generate My Illustrative View" (see IllustrationPanel) — never on
 * render, refresh or a timer. It refuses to send anything unless photo consent
 * is "granted", uploads the front photo for this one request, and turns the
 * answer into an in-memory blob URL. No photo or generated-image bytes are
 * ever written to browser storage.
 */

import { allowsPhotoProcessing } from "../visualization/consent.ts";
import type { PhotoVisualizationConsent } from "../visualization/consent.ts";
import type { TreatmentOpportunity } from "../treatment-opportunities/types.ts";

export type IllustrationOutcome =
  | { status: "ready"; afterUrl: string }
  | { status: "consent_required" | "not_eligible" | "unavailable" | "failed" };

export interface RequestIllustrationInput {
  /** The person's own front photo (a blob URL). */
  photoUrl: string;
  photoQualityValid: boolean;
  opportunities: TreatmentOpportunity[];
  consent: PhotoVisualizationConsent;
  fetchImpl?: typeof fetch;
  /** Turns generated bytes into a reference (defaults to URL.createObjectURL). */
  createObjectUrl?: (blob: Blob) => string;
}

const CLIENT_TIMEOUT_MS = 65_000;

/** Only the fields the server re-derives its plan from — no ids beyond the opportunity's, no observation values. */
const minimal = (o: TreatmentOpportunity) => ({ id: o.id, category: o.category, status: o.status, consumerReady: o.consumerReady, evidenceObservationIds: o.evidenceObservationIds, evidenceQuestionIds: o.evidenceQuestionIds });

export async function requestIllustration(input: RequestIllustrationInput): Promise<IllustrationOutcome> {
  if (!allowsPhotoProcessing(input.consent)) return { status: "consent_required" }; // nothing is fetched, read or sent
  const fetchImpl = input.fetchImpl ?? fetch;
  try {
    const photo = await (await fetchImpl(input.photoUrl)).blob();
    const form = new FormData();
    form.append("photo", photo, "front");
    form.append("payload", JSON.stringify({ photoVisualizationConsent: input.consent, photoQualityValid: input.photoQualityValid, opportunities: input.opportunities.map(minimal) }));
    const response = await fetchImpl("/api/generate-illustration", { method: "POST", body: form, signal: AbortSignal.timeout(CLIENT_TIMEOUT_MS) });
    if (!response.ok) return { status: "failed" };
    const body = (await response.json()) as { status?: string; available?: boolean; image?: { mimeType?: string; base64?: string } };
    if (body.available === false) return { status: "unavailable" };
    if (body.status === "not_eligible") return { status: "not_eligible" };
    if (body.status !== "ready" || !body.image?.base64 || !/^image\/(png|jpeg|webp)$/.test(body.image.mimeType ?? "")) return { status: "failed" };
    const bytes = Uint8Array.from(atob(body.image.base64), (c) => c.charCodeAt(0));
    return { status: "ready", afterUrl: (input.createObjectUrl ?? URL.createObjectURL)(new Blob([bytes], { type: body.image.mimeType })) };
  } catch {
    return { status: "failed" };
  }
}
