/**
 * The browser's side of illustration generation. It runs ONLY when the person
 * clicks "Generate My Illustrative View" (see IllustrationPanel) — never on
 * render, refresh or a timer. It refuses to send anything unless photo consent
 * is "granted", uploads the front photo (and, when the person actually has
 * one, their real left 45°/right 45° photo — never invented) for this one
 * request, and turns each result into an in-memory blob URL. No photo or
 * generated-image bytes are ever written to browser storage.
 *
 * The request carries an `analysisId`/`sessionToken` (see
 * lib/analysis-session/), never a client-computed opportunities list: the
 * server resolves its OWN, independently-computed treatment opportunities
 * from that reference (see lib/image-generation/trustedHandler.ts /
 * multiAngle.ts) — this function has nothing to forge even if it wanted to.
 * All three angles share that one server-side record, so they share the
 * exact same resulting visualization plan — this file cannot make them
 * diverge even by accident.
 */

import { allowsPhotoProcessing } from "../visualization/consent.ts";
import type { PhotoVisualizationConsent } from "../visualization/consent.ts";
import type { VisualizedArea } from "../visualization/present.ts";

export type IllustrationOutcome =
  | { status: "ready"; afterUrl: string }
  | { status: "consent_required" | "not_eligible" | "unavailable" | "failed" };

/** One angle's own result, alongside the primary (front) outcome above — never a fabricated one for an angle that wasn't actually requested or that failed. */
export type SecondaryAngleOutcome = { status: "ready"; afterUrl: string } | { status: "not_eligible" | "unavailable" | "failed" | "not_requested" };

export interface RequestIllustrationInput {
  /** The person's own front photo (a blob URL). Required. */
  photoUrl: string;
  photoQualityValid: boolean;
  /** The person's own real left 45°/right 45° photo (a blob URL) — omit entirely when not actually captured; never substitute another image. */
  leftFortyFivePhotoUrl?: string;
  rightFortyFivePhotoUrl?: string;
  /** The trusted analysis-session handle from AssessmentReview's "Analyze My Face" action (see lib/analysis-session/client.ts). */
  analysisId: string;
  sessionToken: string;
  consent: PhotoVisualizationConsent;
  fetchImpl?: typeof fetch;
  /** Turns generated bytes into a reference (defaults to URL.createObjectURL). */
  createObjectUrl?: (blob: Blob) => string;
}

export interface RequestIllustrationResult {
  front: IllustrationOutcome;
  leftFortyFive: SecondaryAngleOutcome;
  rightFortyFive: SecondaryAngleOutcome;
  /**
   * Which areas were actually illustrated, from the real server-authoritative plan that drove
   * this generation — never the caller's own guess. Absent unless `front` is "ready". The
   * consumer UI must render its "what this illustrates" cards from THIS, not from a locally
   * precomputed preview, which can disagree with what a PredictionPlan-driven generation
   * actually shows (see ResultsExperience.tsx).
   */
  areas?: VisualizedArea[];
}

const CLIENT_TIMEOUT_MS = 3 * 65_000; // up to three sequential image-edit calls server-side

async function toObjectUrl(fetchImpl: typeof fetch, url: string): Promise<Blob> {
  return (await fetchImpl(url)).blob();
}

function decodeAngle(entry: unknown, createObjectUrl: (blob: Blob) => string): SecondaryAngleOutcome {
  if (!entry || typeof entry !== "object") return { status: "failed" };
  const e = entry as { status?: string; image?: { mimeType?: string; base64?: string } };
  if (e.status === "ready" && typeof e.image?.base64 === "string" && /^image\/(png|jpeg|webp)$/.test(e.image.mimeType ?? "")) {
    const bytes = Uint8Array.from(atob(e.image.base64), (c) => c.charCodeAt(0));
    return { status: "ready", afterUrl: createObjectUrl(new Blob([bytes], { type: e.image.mimeType })) };
  }
  if (e.status === "not_eligible" || e.status === "unavailable" || e.status === "not_requested") return { status: e.status };
  return { status: "failed" };
}

/**
 * Requests the front angle (and, when provided, left 45°/right 45°) in ONE
 * request, sharing one trusted analysis session. The return value's `front`
 * field matches the shape existing callers (IllustrationPanel) already
 * expect; `leftFortyFive`/`rightFortyFive` are additive.
 */
export async function requestIllustration(input: RequestIllustrationInput): Promise<RequestIllustrationResult> {
  const notRequested = { status: "not_requested" as const };
  if (!allowsPhotoProcessing(input.consent)) {
    return { front: { status: "consent_required" }, leftFortyFive: notRequested, rightFortyFive: notRequested };
  }
  const fetchImpl = input.fetchImpl ?? fetch;
  const createObjectUrl = input.createObjectUrl ?? URL.createObjectURL;
  try {
    const form = new FormData();
    form.append("photo_front", await toObjectUrl(fetchImpl, input.photoUrl), "front");
    if (input.leftFortyFivePhotoUrl) form.append("photo_leftFortyFive", await toObjectUrl(fetchImpl, input.leftFortyFivePhotoUrl), "left45");
    if (input.rightFortyFivePhotoUrl) form.append("photo_rightFortyFive", await toObjectUrl(fetchImpl, input.rightFortyFivePhotoUrl), "right45");
    form.append("payload", JSON.stringify({ photoVisualizationConsent: input.consent, photoQualityValid: input.photoQualityValid, analysisId: input.analysisId, sessionToken: input.sessionToken }));

    const response = await fetchImpl("/api/generate-illustration", { method: "POST", body: form, signal: AbortSignal.timeout(CLIENT_TIMEOUT_MS) });
    if (response.status === 404 || response.status === 403) {
      return { front: { status: "not_eligible" }, leftFortyFive: notRequested, rightFortyFive: notRequested };
    }
    if (!response.ok) return { front: { status: "failed" }, leftFortyFive: notRequested, rightFortyFive: notRequested };
    const body = (await response.json()) as { status?: string; angles?: Record<string, unknown> };
    const angles = body.angles ?? {};
    const front = decodeAngle(angles.front, createObjectUrl);
    const frontOutcome: IllustrationOutcome = front.status === "ready" ? front : { status: front.status === "not_requested" ? "failed" : front.status };
    const frontEntry = angles.front as { changes?: unknown } | undefined;
    const areas = front.status === "ready" && Array.isArray(frontEntry?.changes) ? (frontEntry.changes as VisualizedArea[]) : undefined;
    return {
      front: frontOutcome,
      leftFortyFive: decodeAngle(angles.leftFortyFive, createObjectUrl),
      rightFortyFive: decodeAngle(angles.rightFortyFive, createObjectUrl),
      areas,
    };
  } catch {
    return { front: { status: "failed" }, leftFortyFive: notRequested, rightFortyFive: notRequested };
  }
}
