/**
 * Browser-side call for the DEVELOPMENT-ONLY supervised illustration test
 * (see devTestHandler.ts). Mirrors client.ts's requestIllustration exactly —
 * the same consent gate, the same one-shot behavior, the same "no image bytes
 * in browser storage" rule — but posts to /api/dev-illustration-test, which
 * the server refuses outright with a 404 unless it is a development server
 * with the explicit test flag set. Never called automatically: only from
 * DevIllustrationTest's explicit button, itself guarded against a second
 * concurrent call (see singleFlight.ts).
 */

import { allowsPhotoProcessing } from "../visualization/consent.ts";
import type { PhotoVisualizationConsent } from "../visualization/consent.ts";

export type DevIllustrationTestOutcome = { status: "ready"; afterUrl: string } | { status: "consent_required" | "disabled" | "failed" };

export interface RequestDevIllustrationTestInput {
  /** The person's own front photo (a blob URL), exactly as the real panel uses it. */
  photoUrl: string;
  photoQualityValid: boolean;
  consent: PhotoVisualizationConsent;
  /** "single" (default) — one expression_lines change. "multi" — the five-area composite preview fixture. Selects which fixed server-side fixture is used; see devTestHandler.ts. */
  fixture?: "single" | "multi";
  fetchImpl?: typeof fetch;
  /** Turns generated bytes into a reference (defaults to URL.createObjectURL). */
  createObjectUrl?: (blob: Blob) => string;
}

const CLIENT_TIMEOUT_MS = 65_000;

export async function requestDevIllustrationTest(input: RequestDevIllustrationTestInput): Promise<DevIllustrationTestOutcome> {
  if (!allowsPhotoProcessing(input.consent)) return { status: "consent_required" }; // nothing is fetched, read or sent
  const fetchImpl = input.fetchImpl ?? fetch;
  try {
    const photo = await (await fetchImpl(input.photoUrl)).blob();
    const form = new FormData();
    form.append("photo", photo, "front");
    form.append("payload", JSON.stringify({ photoVisualizationConsent: input.consent, photoQualityValid: input.photoQualityValid, fixture: input.fixture ?? "single" }));
    const response = await fetchImpl("/api/dev-illustration-test", { method: "POST", body: form, signal: AbortSignal.timeout(CLIENT_TIMEOUT_MS) });
    if (response.status === 404) return { status: "disabled" };
    if (!response.ok) return { status: "failed" };
    const body = (await response.json()) as { status?: string; image?: { mimeType?: string; base64?: string } };
    if (body.status !== "ready" || !body.image?.base64 || !/^image\/(png|jpeg|webp)$/.test(body.image.mimeType ?? "")) return { status: "failed" };
    const bytes = Uint8Array.from(atob(body.image.base64), (c) => c.charCodeAt(0));
    return { status: "ready", afterUrl: (input.createObjectUrl ?? URL.createObjectURL)(new Blob([bytes], { type: body.image.mimeType })) };
  } catch {
    return { status: "failed" };
  }
}
